=head1 Issues fixed after release 20201207

=over 4

=item B<Improve alignment of leading equals in rare situation>

A rare case in which a vertical alignment opportunity of leading equals was
missed has been fixed. This involved lines with additional varying alignment
tokens, such as 'unless' and second '=' in lines 1-3 below.  In this example
lines 4 and 5 were not 'looking' backwards to align their leading equals.

    # OLD:
    $them = 'localhost' unless ( $them = shift );
    $cmd  = '!print'    unless ( $cmd  = shift );
    $port = 2345        unless ( $port = shift );
    $saddr = 'S n a4 x8';
    $SIG{'INT'} = 'dokill';
    
    # NEW
    $them       = 'localhost' unless ( $them = shift );
    $cmd        = '!print'    unless ( $cmd  = shift );
    $port       = 2345        unless ( $port = shift );
    $saddr      = 'S n a4 x8';
    $SIG{'INT'} = 'dokill';

Fixed 5 Jan 2021.

=item B<Moved previous patch to a better location>

The previous patch was moved to a location where it only applies if
there is a side comment on the line with a closing token.  This minimizes
changes to other side comment locations.

=item B<Further improvement in rules for forgetting last side comment location>

The code for forgetting the last side comment location was rewritten to improve
formatting in some edge cases.  The update also fixes a very rare problem
discovered during testing and illustrated with the following snippet.  The
problem occurs for the particular combination of parameters -sct -act=2 and
when a closing paren has a side comment:

    OLD: perltidy -sct -act=2
    foreach $line (
        [0, 1, 2], [3, 4, 5], [6, 7, 8],    # rows
        [0, 3, 6], [1, 4, 7], [2, 5, 8],    # columns
        [0, 4, 8], [2, 4, 6])                                     # diagonals

    NEW: perltidy -sct -act=2
    foreach $line (
        [0, 1, 2], [3, 4, 5], [6, 7, 8],    # rows
        [0, 3, 6], [1, 4, 7], [2, 5, 8],    # columns
        [0, 4, 8], [2, 4, 6])    # diagonals

In the old version the last side comment was aligned before the closing paren
was attached to the previous line, causing the final side comment to be far to
the right.  A patch in the new version just places it at the default location.
This is the best than can be done for now, but is preferable to the old
formatting. 3 Jan 2021, e57d8db.

=item B<Improve rule for forgetting last side comment location>

The code which aligns side comments remembers the most recent side comment and
in some cases tries to start aligning at that column for later side comments.
Sometimes the old side comment column was being remembered too long, causing
occasional poor formatting and causing a noticable and unexpected drift of side
comment locations to the right.  The rule for forgetting the previous side
comment column has been modified to reduce this problem.  The new rule is
essentially to forget the previous side comment location at a new side comment
with different indentation level or significant number of lines without side
comments (about 12).  The previous implementation forgetting changes in
indentation level across code blocks only.  Below is an example where the old
method gets into trouble and the new method is ok:

        # OLD:
        foreach my $r (@$array) {
            $Dat{Data}{ uc $r->[0] } = join( ";", @$r );    # store all info
            my $name = $Dat{GivenName}{ uc $r->[0] } || $r->[1];

            # pass array as ad-hoc string, mark missing values
            $Dat{Data}{ uc $r->[0] } = join(
                ";",
                (
                    uc $r->[0], uc $name,                   # symbol, name
                    $r->[2],    $r->[3], $r->[4],           # price, date, time
                    $r->[5],    $r->[6],                    # change, %change
                    $r->[7],    "-", "-", "-",    # vol, avg vol, bid,ask
                    $r->[8],               $r->[9],     # previous, open
                    "$r->[10] - $r->[11]", $r->[12],    # day range,year range,
                    "-",                   "-", "-", "-", "-"
                )
            );                                          # eps,p/e,div,yld,cap
        }

The second side comment is at a deeper indentation level but was not being forgotten,
causing line length limits to interfere with later alignment. The new rule gives
a better result:

        # NEW:
        foreach my $r (@$array) {
            $Dat{Data}{ uc $r->[0] } = join( ";", @$r );    # store all info
            my $name = $Dat{GivenName}{ uc $r->[0] } || $r->[1];

            # pass array as ad-hoc string, mark missing values
            $Dat{Data}{ uc $r->[0] } = join(
                ";",
                (
                    uc $r->[0], uc $name,               # symbol, name
                    $r->[2],    $r->[3], $r->[4],       # price, date, time
                    $r->[5],    $r->[6],                # change, %change
                    $r->[7],    "-", "-", "-",          # vol, avg vol, bid,ask
                    $r->[8],               $r->[9],     # previous, open
                    "$r->[10] - $r->[11]", $r->[12],    # day range,year range,
                    "-",                   "-", "-", "-", "-"
                )
            );    # eps,p/e,div,yld,cap
        }

The following exampel shows an unexpected alignment in the cascade of trailing
comments which are aligned but slowly separating from their closing containers:

    # OLD:
    {
        $a = [
            Cascade    => $menu_cb,
            -menuitems => [
                [ Checkbutton => 'Oil checked', -variable => \$OIL ],
                [
                    Button   => 'See current values',
                    -command => [
                        \&see_vars, $TOP,

                    ],    # end see_vars
                ],        # end button
            ],            # end checkbutton menuitems
        ];                # end checkbuttons cascade
    }

This was caused by forgetting side comments only across code block changes. The new
result is more reasonable: 

    # NEW:
    {
        $a = [
            Cascade    => $menu_cb,
            -menuitems => [
                [ Checkbutton => 'Oil checked', -variable => \$OIL ],
                [
                    Button   => 'See current values',
                    -command => [
                        \&see_vars, $TOP,

                    ],    # end see_vars
                ],    # end button
            ],    # end checkbutton menuitems
        ];    # end checkbuttons cascade
    }

This change will cause occasional differences in side comment locations from
previous versions but overall it gives fewer unexpected results so it is a worthwhile
change.  29-Dec-2020, 76993f4.

=item B<Fixed very minor inconsistency in redefining lists after prune step>

In rare cases it is necessary to update the type of lists, and this
influences vertical alignment. This update fixes a minor inconsistency
in doing this.  In some rare cases with complex list elements vertical
alignment can be improved.  27 Dec, 2020, 751faec.

            # OLD
            return join( '',
                $pre,   '<IMG ',   $iconsizes{$alt} || '',
                $align, 'BORDER=', $nav_border,
                ' ALT="', $alt,        "\"\n",
                ' SRC="', $ICONSERVER, "/$icon",
                '">' );

            # NEW
            return join( '',
                $pre,     '<IMG ',     $iconsizes{$alt} || '',
                $align,   'BORDER=',   $nav_border,
                ' ALT="', $alt,        "\"\n",
                ' SRC="', $ICONSERVER, "/$icon",
                '">' );

=item B<Improved vertical alignment of some edge cases>

The existing rules for aligning two lines with very different lengths were
rejecting some good alignments, such as the first line of numbers in the example
below:

    # OLD:
    @gg_3 = (
        [
            0.0, 1.360755E-2, 9.569446E-4, 9.569446E-4,
            1.043498E-3, 1.043498E-3
        ],
        [
            9.569446E-4, 9.569446E-4, 0.0, 7.065964E-5,
            1.422811E-4, 1.422811E-4
        ],
        ...
    );

    # NEW:
    @gg_3 = (
        [
            0.0,         1.360755E-2, 9.569446E-4, 9.569446E-4,
            1.043498E-3, 1.043498E-3
        ],
        [
            9.569446E-4, 9.569446E-4, 0.0, 7.065964E-5,
            1.422811E-4, 1.422811E-4
        ],
        ...
    );

The rule in sub 'two_line_pad' was updated to allow alignment of any lists
if the patterns match exactly (all numbers in this case).  Updated
27-Dec-2020, 035d2b7.

=item B<Avoid -lp style formatting of lists containing multiline qw quotes>

The -lp formatting style often does not work well when lists contain multiline qw
quotes.  This update avoids this problem by not formatting such lists with the
-lp style.  For example,

    # OLD, perltidy -gnu
    @EXPORT = (
        qw(
          i Re Im rho theta arg
          sqrt log ln
          log10 logn cbrt root
          cplx cplxe
          ),
        @trig,
              ); 


    # NEW, perltidy -gnu
    @EXPORT = (
        qw(
          i Re Im rho theta arg
          sqrt log ln
          log10 logn cbrt root
          cplx cplxe
        ),
        @trig,
    );

27-Dec-2020, 948c9bd.

=item B<improve formatting of multiline qw>

This update adds a sequence numbering system for multiline qw quotes.  In the
perltidy tokenizer normal container pair types, like { }, (), [], are given
unique serial numbers which are used as keys to data structures.  qw quoted
lists do not get serial numbers by the tokenizer, so this update creates a
separate serial number scheme for them to correct this problem.  One formatting
problem that this solves is that of preventing the closing token of a multiline
quote from being outdented more than the opening token.  This is a general
formatting rule which should be followed. Without a sequence
number, the closing qw token could not lookup its corresponding opening
indentation so it had to resort to a default, breaking the rule, as in the following:

    # OLD, perltidy -wn
    # qw line
    if ( $pos == 0 ) {
        @return = grep( /^$word/,
            sort qw(
              ! a b d h i m o q r u autobundle clean
              make test install force reload look
        ) ); #<-- outdented more than 'sort'
    }

    # Here is the same with a list instead of a qw; note how the
    # closing sort paren does not outdent more than the 'sort' line.
    # This is the desired result for qw.
    # perltidy -wn
    if ( $pos == 0 ) {
        @return = grep( /^$word/,
            sort (

                '!',          'a', 'b', 'd', 'h', 'i', 'm', 'o', 'q', 'r', 'u',
                'autobundle', 'clean',
                'make',       'test', 'install', 'force', 'reload', 'look'
            ) );  #<-- not outdented more than 'sort'
    }

    # NEW (perltidy -wn)
    if ( $pos == 0 ) {
        @return = grep( /^$word/,
            sort qw(
              ! a b d h i m o q r u autobundle clean
              make test install force reload look
            ) ); #<-- not outdented more than sort
    }

Here is another example
    # OLD:
    $_->meta->make_immutable(
        inline_constructor => 0,
        constructor_name   => "_new",
        inline_accessors   => 0,
        )
        for qw(
        Class::XYZ::Package
        Class::XYZ::Module
        Class::XYZ::Class

        Class::XYZ::Overload
    );  #<-- outdented more than the line with 'for qw('

    # NEW:
    $_->meta->make_immutable(
        inline_constructor => 0,
        constructor_name   => "_new",
        inline_accessors   => 0,
      )
      for qw(
      Class::XYZ::Package
      Class::XYZ::Module
      Class::XYZ::Class

      Class::XYZ::Overload
      ); #<-- outdented same as the line with 'for qw('

26 Dec 2020, cdbf0e4.

=item B<improve list marking method>

In the process of making vertical alignments, lines which are simple lists of
items are treated different from other lines. The old method for finding and
marking these lines had a few problems which are corrected with this update.
The main problem was that the old method ran into trouble when there were side
comments.  For example, the old method was not marking the following list and
as a result the two columns of values were not aligned:

    # OLD
    return (
        $startpos, $ldelpos - $startpos,         # PREFIX
        $ldelpos,  1,                            # OPENING BRACKET
        $ldelpos + 1, $endpos - $ldelpos - 2,    # CONTENTS
        $endpos - 1, 1,                          # CLOSING BRACKET
        $endpos, length($$textref) - $endpos,    # REMAINDER
    );

    # NEW
    return (
        $startpos,    $ldelpos - $startpos,           # PREFIX
        $ldelpos,     1,                              # OPENING BRACKET
        $ldelpos + 1, $endpos - $ldelpos - 2,         # CONTENTS
        $endpos - 1,  1,                              # CLOSING BRACKET
        $endpos,      length($$textref) - $endpos,    # REMAINDER
    );

Another problem was that occasionally unwanted alignments were made between
lines which were not really lists because the lines were incorrectly marked.
For example (note padding after first comma)

    # OLD: (undesirable alignment)
    my ( $isig2, $chisq ) = ( 1 / ( $sig * $sig ), 0 );
    my ( $ym,    $al, $cov, $bet, $olda, $ochisq, $di, $pivt, $info ) =
      map { null } ( 0 .. 8 );

    # NEW: (no alignment)
    my ( $isig2, $chisq ) = ( 1 / ( $sig * $sig ), 0 );
    my ( $ym, $al, $cov, $bet, $olda, $ochisq, $di, $pivt, $info ) =
      map { null } ( 0 .. 8 );

This update was made 22 Dec 2020, 36d4c35.

=item B<Fix git #51, closing quote pattern delimiters not following -cti flag settings>

Closing pattern delimiter tokens of qw quotes were not following the -cti flag
settings for containers in all cases, as would be expected, in particular when
followed by a comma.  For example, the closing qw paren below was indented with
continuation indentation but would not have that extra indentation if it
followed the default -cpi setting for a paren: 

    # OLD:
    @EXPORT = (
        qw(
          i Re Im rho theta arg
          sqrt log ln
          log10 logn cbrt root
          cplx cplxe
          ),
        @trig
    );

    # NEW
    @EXPORT = (
        qw(
            i Re Im rho theta arg
            sqrt log ln
            log10 logn cbrt root
            cplx cplxe
        ),
        @trig
    );

This update makes closing qw quote terminators follow the settings for their
corresponding container tokens as closely as possible.  For a closing '>'
the setting for a closing paren will now be followed.  Other closing qw 
terminators will remain indented, to minimize changes to existing formatting.  
For example ('>' is outdented):

    @EXPORT = (
        qw<
          i Re Im rho theta arg
          sqrt log ln
          log10 logn cbrt root
          cplx cplxe
        >,
        @trig
    );

but (';' remains indented):

    @EXPORT = (
        qw;
          i Re Im rho theta arg
          sqrt log ln
          log10 logn cbrt root
          cplx cplxe
          ;,
        @trig
    );

This update was added 18 Dec 2020 and modified 24 Dec 2020, 538688f.

=item B<Update manual pages regarding issue git #50>

Additional wording was added to the man pages regarding situations in which
perltidy does not change whitespace.  This update was added 17 Dec 2020.

=item B<Rewrote sub check_match>

Moved inner part of sub check_match into sub match_line_pair in order to
make info available earlier.  This gave some minor alignment improvements.
This was done 16 Dec 2020, 7ba4f3b.

    # OLD:
    @tests = (
        @common,     '$_',
        '"\$_"',     '@_',
        '"\@_"',     '??N',
        '"??N"',     chr 256,
        '"\x{100}"', chr 65536,
        '"\x{10000}"', ord 'N' == 78 ? ( chr 11, '"\013"' ) : ()
    );

    # NEW:
    @tests = (
        @common,       '$_',
        '"\$_"',       '@_',
        '"\@_"',       '??N',
        '"??N"',       chr 256,
        '"\x{100}"',   chr 65536,
        '"\x{10000}"', ord 'N' == 78 ? ( chr 11, '"\013"' ) : ()
    );

=item B<Improved vertical alignments by avoiding pruning step>

There is a step in vertical alignment where the alignments are formed into a
tree with different levels, and some deeper levels are pruned to preserve
lower level alignments.  This usually works well, but some deeper alignments
will be lost, which is what was happening in the example below.  It turns out
that if the tree pruning is skipped when alignment depths increase
monotonically across lines, as in the example, then better overall alignment is
achieved by the subsequent 'sweep' pass. 

    # OLD
    my $cmd = shift @ARGV;
    if    ( $cmd eq "new" )         { $force_new = 1; }
    elsif ( $cmd eq "interactive" ) { $interactive = 1; $batch       = 0; }
    elsif ( $cmd eq "batch" )       { $batch       = 1; $interactive = 0; }
    elsif ( $cmd eq "use_old" )     { $use_old = 1; }
    elsif ( $cmd eq "show" )        { $show    = 1; last; }
    elsif ( $cmd eq "showall" )     { $showall = 1; last; }
    elsif ( $cmd eq "show_all" )    { $showall = 1; last; }
    elsif ( $cmd eq "remove" )      { $remove  = 1; last; }
    elsif ( $cmd eq "help" )        { $help    = 1; last; }

    # NEW
    my $cmd = shift @ARGV;
    if    ( $cmd eq "new" )         { $force_new   = 1; }
    elsif ( $cmd eq "interactive" ) { $interactive = 1; $batch       = 0; }
    elsif ( $cmd eq "batch" )       { $batch       = 1; $interactive = 0; }
    elsif ( $cmd eq "use_old" )     { $use_old     = 1; }
    elsif ( $cmd eq "show" )        { $show        = 1; last; }
    elsif ( $cmd eq "showall" )     { $showall     = 1; last; }
    elsif ( $cmd eq "show_all" )    { $showall     = 1; last; }
    elsif ( $cmd eq "remove" )      { $remove      = 1; last; }
    elsif ( $cmd eq "help" )        { $help        = 1; last; }

This update was made 14 Dec 2020, 44e0afa.

=item B<Improved some marginal vertical alignments>

This update fixed a rare situation in which some vertical alignment was missed.
The problem had to do with two lines being incorrectly marked as a marginal
match. A new routine, 'match_line_pairs' was added to set a flag with the
information needed to detect and prevent this. This fix was made 13 Dec 2020, 9a8e49b.

    # OLD
    $sec = $sec + ( 60 * $min );
    $graphcpu[$sec] = $line;
    $secmax  = $sec  if ( $sec > $secmax );
    $linemax = $line if ( $line > $linemax );

    # NEW
    $sec            = $sec + ( 60 * $min );
    $graphcpu[$sec] = $line;
    $secmax         = $sec  if ( $sec > $secmax );
    $linemax        = $line if ( $line > $linemax );

=item B<Do not align equals across changes in continuation indentation>

A rule was added to prevent vertical alignment of lines with leading '=' across
a change in continuation indentation. Sometimes aligning across a change in CI
can come out okay, but sometimes it can be very poor. For example:

    # BAD:
    $!               = 2, die qq/$0: can't stat -${arg}'s "$file"./
	unless $time = ( stat($file) )[$STAT_MTIME];

    # FIXED:
    $! = 2, die qq/$0: can't stat -${arg}'s "$file"./
      unless $time = ( stat($file) )[$STAT_MTIME];

The second line is a continuation of the first, and this update prevents this
alignment.  The above 'BAD' formatting was in the previous developmental
version of perltidy, not the previous release. This update added 12 Dec 2020, 5b56147.

=item B<Improve vertical alignment in some two-line matches>

When two lines would be perfectly aligned except for the line length limit,
previously they would only be aligned if they had a common leading equals.  The
update removes this restriction and allows as many alignments to be made as
possible.  The results are generally improved.  This update was made 11 Dec 2020,
f3c6cd8.  Some examples:

# In this example the side comments were limiting the matches

    # OLD
    shift @data if @data and $data[0] =~ /Contributed\s+Perl/;    # Skip header
    pop @data if @data and $data[-1] =~ /^\w/;    # Skip footer, like

    # NEW
    shift @data if @data and $data[0]  =~ /Contributed\s+Perl/;    # Skip header
    pop @data   if @data and $data[-1] =~ /^\w/;    # Skip footer, like

# The same is true here.

    # OLD
    if ($tvg::o_span) { $tvg::hour_span = $tvg::o_span; }
    if ( $tvg::hour_span % 2 > 0 ) { $tvg::hour_span++; }    # Multiple of 2

    # NEW
    if ($tvg::o_span)              { $tvg::hour_span = $tvg::o_span; }
    if ( $tvg::hour_span % 2 > 0 ) { $tvg::hour_span++; }    # Multiple of 2

In the next example, the first comma is now aligned but not the second, because
of the line length limit:

    # OLD
    is( MyClass->meta, $mc, '... these metas are still the same thing' );
    is( MyClass->meta->meta, $mc->meta, '... these meta-metas are the same thing' );

    # NEW
    is( MyClass->meta,       $mc, '... these metas are still the same thing' );
    is( MyClass->meta->meta, $mc->meta, '... these meta-metas are the same thing' );

In this last example, the first comma is not aligned, but alignment resumes
after the second comma.

    # OLD
    is( $obj->name, $COMPRESS_FILE, "   Name now set to '$COMPRESS_FILE'" );
    is( $obj->prefix, '', "   Prefix now empty" );

    # NEW
    is( $obj->name, $COMPRESS_FILE, "   Name now set to '$COMPRESS_FILE'" );
    is( $obj->prefix, '',           "   Prefix now empty" );

=item B<Improve vertical alignment in some marginal matches>

In perltidy a 'marginal match' occurs for example when two lines share some
alignment tokens but are somewhat different.  When this happens some limits are
placed on the size of the padding spaces that can be introduced.  In this
update the amount of allowed padding is significatly increased for certain
'good' alignment tokens.  Results of extensive testing were favorable provided 
that the change is restricted to alignments of '=', 'if' and 'unless'.  Update
made 10 Dec 2020, a585f0b.

    # OLD
    my @roles = $self->role_names;
    my $role_names = join "|", @roles;

    # NEW
    my @roles      = $self->role_names;
    my $role_names = join "|", @roles;

    # OLD
    $sysname .= 'del' if $self->label =~ /deletion/;
    $sysname .= 'ins' if $self->label =~ /insertion/;
    $sysname .= uc $self->allele_ori->seq if $self->allele_ori->seq;

    # NEW
    $sysname .= 'del'                     if $self->label =~ /deletion/;
    $sysname .= 'ins'                     if $self->label =~ /insertion/;
    $sysname .= uc $self->allele_ori->seq if $self->allele_ori->seq;

=item B<Improve vertical alignment of lines ending in fat comma>

A minor adjustment was made to the rule for aligning lines which end in '=>'.
When there are just two lines in an alignment group, the alignment is avoided
if the first of the two ends in a '=>'.  Previously, alignment was avoided
if either ended in a '=>'.  The old rule was preventing some good alignments 
in a later stage of the iteration.  In the following example, the last
two lines are processed separately because they do not match the comma
in 'sprintf'.  The new rule allows the fat comma alignment to eventually
get made later in the iteration. Update made 9 Dec 2020, ca0ddf4.

    # OLD 
    $template->param(
        classlist => $classlist,
        ...,
        suggestion => $suggestion,
        totspent   => sprintf( "%.2f", $totspent ),
        totcomtd   => sprintf( "%.2f", $totcomtd ),
        totavail   => sprintf( "%.2f", $totavail ),
        nobudget => $#results == -1 ? 1 : 0,
        intranetcolorstylesheet =>
          C4::Context->preference("intranetcolorstylesheet"),
        ...
    );

    # NEW
    $template->param(
        classlist => $classlist,
        ...,
        suggestion              => $suggestion,
        totspent                => sprintf( "%.2f", $totspent ),
        totcomtd                => sprintf( "%.2f", $totcomtd ),
        totavail                => sprintf( "%.2f", $totavail ),
        nobudget                => $#results == -1 ? 1 : 0,
        intranetcolorstylesheet =>
          C4::Context->preference("intranetcolorstylesheet"),
        ...
    );

=item B<Avoid processing a file more than once>

In the unlikely event that  a user enters a filename more than once on the
command line to perltidy, as for 'file1.pl' here
   
  perltidy file1.pl file1.pl 

then that file will be processed more than once. This looks harmless, but if
the user was also using the -b (backup) parameter, then the original backup
would be overwritten, which is not good.  To avoid this, a filter has been
placed on the list of files to remove duplicates.  9 Dec 2020, 646a542.

=back

=item B<Fix for issue git #49, exit status not correctly set>

The exit status flag was not being set for the -w option if the -se or if the -q flag
were set.  Issue git #44 was similar but a special case of the problem.  The 
problem was fixed 8 Dec 2020, cb6028f.

=back

=head1 Issues fixed after release 20201202

=over 4

=item B<Fix for issue git #47>

This issue has to do with the --weld-nested-containers option in the specific
case of formatting a function which returns a list of anonymous subs.  For
example

    $promises[$i]->then(
        sub { $all->resolve(@_); () },
        sub {
            $results->[$i] = [@_];
            $all->reject(@$results) if --$remaining <= 0;
            return ();
        }
    );

A bug introduced in v20201202 caused an incorrect welding to occur
when the -wn flag was set

    $promises[$i]->then( sub { $all->resolve(@_); () },
        sub {
        $results->[$i] = [@_];
        $all->reject(@$results) if --$remaining <= 0;
        return ();
        } );

This bug has been fixed, and code which has been incorrectly formatted will be
correctly formatted with the next release.  The bug was a result of a new
coding introduced in v20201202 for fixing some issues with parsing sub
signatures.  Previously they were sometimes parsed the same as prototypes and
sometimes as lists, now they are always parsed as lists. Fixed 6 Dec 2020, 6fd0c4f.

=back

=head1 Issues fixed after release 20201001

=over 4

=item B<removed excess spaces in a package declaration>

Testing revealed that for a line such as

   package        Bob::Dog;

which has extra spaces or even tabs after the keyword 'package', the
extra spaces or tabs were not being removed.  This was fixed 28 Nov 2020, 008443d.
The line now formats to

    package Bob::Dog;

=item B<do not automatically delete closing side comments with --indent-only>

For the parameter combination --indent-only and --closing-side-comments, old
closing side comments were getting deleted but new closing side comments were
not made.  A fix was made to prevent this deletion.  This fix was made 27 Nov 2020, 957e0ca.

=item B<fix to stop at 1 iteration when using --indent-only>

Previously, for the combination --indent-only and -conv, two iterations
would be done.  Only one iteration is necessary in this case.  Fix made 23 Nov 2020, ae493d8.

=item B<fix for formatting signed numbers with spaces>

In developing an improved convergence test, an issue slowing convergence
was found related to signed numbers as in the following line, 

    @london = (deg2rad(-  0.5), deg2rad(90 - 51.3));

The leading '-' here is separated from the following number '0.5'. This is handled
by tokenizing the minus as type 'm' and the number as type 'n'.  The whitespace
between them is removed in formatting, and so the space is gone in the output.
But a little problem is that the default rule for placing spaces within the
parens is based on the token count, after the first formatting the result is

    @london = ( deg2rad( -0.5 ), deg2rad( 90 - 51.3 ) );

The next time it is formatted, the '-0.5' counts as one token, resulting in 

    @london = ( deg2rad(-0.5), deg2rad( 90 - 51.3 ) );

Notice that the space within the parens around the '-0.5' is gone. An update
was made to fix this, so that the final state is reached in one step.  This fix
was made 23 Nov 2020, f477c8b.

=item B<fix to prevent conversion of a block comment to hanging side comment>

A rare situation was identified during testing in which a block comment could
be converted to be a hanging side comment.  For example:

    sub macro_get_names {    #
    #
    # %name = macro_get_names();  (key=macrohandle, value=macroname)
    #
        local (%name) = ();
        ...
    }

For the following specific contitions the block comment in line 2 could be
converted into a hanging side comment, which is undesirable:

   1. The line contains nothing except for a '#' with no leading space
   2. It follows a line with side comment
   3. It has indentation level > 0

An update was made to prevent this from happening.  There are two cases,
depending on the value of --maximum-consecutive-blank-lines, or -mbl.  If this
value is positive (the default) then a blank line is inserted above the block
comment to prevent it from becoming a hanging side comment.  If this -mbl is
zero, then the comment is converted to be a static block comment which again
prevents it from becoming a hanging side comment. This fix was made 23 Nov
2020, 2eb3de1.

=item B<improved convergence test>

A better test for convergence has been added. When iterations are requested,
the new test will stop after the first pass if no changes in line break
locations are made.  Previously, at least two passes were required to verify
convergnece unless the output stream had the same checksum as the input stream.
Extensive testing has been made to verify the correctness of the new test.
This update was made 23 Nov 2020, 29efb63.

=item B<fixed problem with vertical alignments involving 'if' statements>

An update was made to break vertical alignment when a new sequence of if-like
statements or ternary statements is encountered.  This situation was causing a
loss of alignment in some cases.  For example

  OLD:
    $m1 = 0;
    if ( $value =~ /\bset\b/i )      { $m0 = 1; }
    if ( $value =~ /\barithmetic/i ) { $m1 = 1; }
    if    ( $m0 && !$m1 ) { $CONFIG[1] = 0; }
    elsif ( !$m0 && $m1 ) { $CONFIG[1] = 1; }
    else                  { $ok        = 0; last; }

 NEW:
    $m1 = 0;
    if    ( $value =~ /\bset\b/i )      { $m0        = 1; }
    if    ( $value =~ /\barithmetic/i ) { $m1        = 1; }
    if    ( $m0 && !$m1 )               { $CONFIG[1] = 0; }
    elsif ( !$m0 && $m1 )               { $CONFIG[1] = 1; }
    else                                { $ok        = 0; last; }

This update was made 15 Nov 2020, 2b7784d.

=item B<added option -wnxl=s to give control of welding by the -wn parameter>

The parameter string can restrict the types of containers which are welded. This
was added 11 Nov 2020 in 'added -wnxl=s for control of -wn', 2e642d2.

=item B<merged pull request git #46>

The man page gave the incorrect string for -fse. This was fixed 11 Nov 2020 in 1f9869e.

=item B<recognize overloaded RPerl operators to avoid error messages>

RPerl uses some bareword operators which caused error messages.  An update
was made to avoid this problem in files containing 'use RPerl'. This update was
made 6 Nov 2020, f8bd088.

=item B<fix issue git #45, -wn and -vtc=n now work together>

When -wn was set, the -vtc=n flag was being ignored.  This was a simple fix
made 5 Nov 2020 in 'fix issue git #45, -wn and -vtc=n now work together', 1fbc381.

=item B<implement request RT #133649, added parameters -kbb=s and -kba=s>

These parameters request that old breakpoints be kept before or after
selected token types.  For example, -kbb='=>' means that newlines before
fat commas should be kept. This was added 4 Nov 2020.

=item B<added parameters -maxue=n and maxle=n>

These parameters had tentatively been hardwired in the tokenizer.
Now the user can control them or turn the checks off altogether.

=item B<Fix problem parsing '$$*'>

In random testing, an error was encountered parsing the following line

  $self->{"mod_id"}=($$*1001)%(10**(rand()*6));
                       ---^
  found Number where operator expected (previous token underlined)

The line parsed correctly with a space between the '$$' and the '*'. The
problem had to do with an error in some newer code for postfix dereferencing,
and this was fixed on 2 Nov 2020,  
'fix problem scanning '$$'; revise call to operator_expected', 49d993b.

=item B<Update for git #44, fix exit status for assert-tidy/untidy>

The exit status was always 0 for --assert-tidy if the user had turned off error
messages with -quiet.  This was fixed by gluesys/master in 'fix exit
status for assert-tidy/untidy options', 625d250.

=item B<Fixed problem parsing extruded signature>

A parsing error was encountered in a test parsing the following extruded
signature:

  sub foo2
  (
  $
  first
  ,
  $
  ,
  $
  third
  )
  {
  return
  "first=$first, third=$third"
  ;
  }

The second '$' combined with the ',' on the next line to form a punctuation variable.
This was fixed 20 Oct 2020 in 'fixed problem parsing extruded signature', 9b454f6.

The file parses correctly now, with formatted output

  sub foo2 ( $first, $, $third ) {
      return "first=$first, third=$third";
  }

=item B<Fixed several uses of undefined variables found in testing>

Several instances of incorrect array indexing were found in testing and fixed.
These each involved incorrectly indexing with index -1. They were found by
placing undefs at the end of arrays.  None of these was causing incorrect
formatting. They were fixed 26 Oct 2020 in 'fixed several instances of
incorrect array indexing', c60f694.

=item B<Prevent syntax error by breaking dashed package names>

In stress testing perltidy with the -extrude option, the following test snippet 

  use perl6-alpha;

was broken into sepate lines

  use
  perl6
  -
  alpha
  ;

A rule was added to prevent breaking around a dash separating two barewords.
Rerunning gives

  use
  perl6-alpha
  ;

This was fixed 26 Oct 2020 in 'prevent breaking package names with trailing dashes', 9234be4.

=item B<Prevent syntax error by breaking dashed barewords>

In stress testing perltidy with the -extrude option, using the following test snippet

  my %var;
  {
      $var{-y}  = 1;
      $var{-q}  = 1;
      $var{-qq} = 1;
      $var{-m}  = 1;
      $var{y}   = 1;
      $var{q}   = 1;
      $var{qq}  = 1;
      $var{m}   = 1;
  }

a syntax error was created when newlines were placed
before or after the dashes.  It is necessary to always keep a dash on the same
line with its surrounding tokens.  A rule was added to do this.  The new
'extruded' result for the above snippet is:

  my%var
  ;
  {
  $var{-y}
  =
  1
  ;
  $var{-q}
  =
  1
  ;
  $var{-qq}
  =
  1
  ;
  $var{-m}
  =
  1
  ;
  $var{y}
  =
  1
  ;
  $var{q}
  =
  1
  ;
  $var{qq}
  =
  1
  ;
  $var{m}
  =
  1
  ;
  }

This update was added 26 Oct 2020, 'prevent syntax error by breaking dashed
barewords', e121cae.

=item B<more types of severe errors will prevent formatting>

Files for which 'severe errors' are found have always been output verbatim
rather than being formatted.  The definition of 'severe error' has been
expanded to include a final indentation level error greater than 1, more than 2
brace errors, and more than 3 "unexpected token type" parsing errors.  The goal
is to avoid formatting a non-perl script or a perl script with severe errors.
So for example the following snippet has a level error of 2

  {{{{
  }}

was previously output with default parameters as

  { 
      {
          {
              {}
          }


along with an error message. But now it is just output verbatim as

  {{{{
  }}

along with an error message.  This update was added 25 Oct 2020,
'avoid formatting files with more types of severe errors', 2a86f51.

=item B<added 'state' as keyword>

A statement such as the following was generating an error message at the colon:

   state $a : shared;

The problem was that 'state' was not in the list of keywords. This has been fixed
and the line now parses without error.  The 'state.t' test file for perl 5.31
now formats without error.  This was added 18 Oct 2020 in "add 'state' as keyword",
d73e15f.

=item B<sub signatures no longer parsed with prototypes>

Simple signatures (those without commas) were being parsed with code originally
written for prototypes. This prevented them from being formatted with the
usual formatting rules.  This was changed so that all signatures are now
formatted with the normal formatting rules. For example:

 # Old, input and after formatting:
 sub t123 ($list=wantarray) { $list ? "list" : "scalar" }

 # New, after formatting
 sub t123 ( $list = wantarray ) { $list ? "list" : "scalar" }

Notice that some spaces have been introduced within the signature. Previously
the contents of the parens not changed unless the parens contained a list.

This change introduced a problem parsing extended syntax within
signatures which has been fixed. In the following snippet, the ':' caused
a parsing error which was fixed.

  # perltidy -sal='method'
  method foo4 ( $class : $bar, $bubba ) { $class->bar($bar) }

The ':' here is given a type of 'A'. This may be used to change
the spacing around it. For example:

  # perltidy -sal='method' -nwls='A'
  method foo4 ( $class: $bar, $bubba ) { $class->bar($bar) }

This update was added 18 Oct 2020, in 'format all signatures separately from
prototypes', e6a10f3.  The test file 'signatures.t' distributed with perl5.31
formats without error now.

=item B<fix parsing problem with $#>

A problem with parsing variables of the form $# and $#array was found in
testing and fixed.  For most variables the leading sigil may be separated from
the remaining part of the identifier by whitespace.  An exception is for a
variable beginning with '$#'.  If there is any space between the '$' and '#'
then the '#' starts a comment.  So the following snippet is has valid syntax
and is equivalent to $ans=40;

    my $ #
    #
    ans = 40;

This was being misparsed and was fixed 17 Oct 2020,  in
'fixed parsing error with spaces in $#' a079cdb.

=item B<fix missing line break for hash of subs with signatures>

During testing the following error was found and fixed.
Given the following input snippet:

    get(
        on_ready => sub ($worker) {
            $on_ready->end;
            return;
        },
        on_exit => sub ( $worker, $status ) { return; },
    );

The resulting formatting was

    get(
        on_ready => sub ($worker) {
            $on_ready->end;
            return;
        }, on_exit => sub ( $worker, $status ) { return; },
    );

Notice that the break after the comma has been lost.  The problem was traced to
a short-cut taken by the code looking for one-line blocks. The unique
circumstances in which this occured involved a hash of anonymous subs, one with
a signature with multiple parameters and short enough to be a one-line block,
as in the last sub definition line.  This was fixed 17 Oct 2020
in 'fix missing line break for hash of subs with signatures', 51428db.

=item B<fix issues with prototype and signature parsing>

Problems with parsing prototypes and signatures were found during testing and
fixed 17 Oct 2020 in 'fixed problem parsing multi-line signatures with
comments', 017fd07.  For example the following snippet was mis-parsed because
of the hash mark. 

    sub test ( # comment ))) 
        $x, $x) { $x+$y }


Complex signature expressions such as the following are now parsed without
error:

    sub t086
        ( #foo)))
        $ #foo)))
        a #foo)))
        ) #foo)))
        { $a.$b }

=item B<improve guess for pattern or division>

The following line caused a tokenization error in which the two slashes
were parsed as a pattern.  

   my $masksize = ceil( Opcode::opcodes / 8 );    # /

This problem was discovered in random testing.  When a slash follows a bareword
whose prototype is not known to perltidy, it has to guess whether the slash
starts a pattern or is a division.  The guessing logic was rewritten and 
improved 14 Oct 2020 in 'rewrote logic to guess if divide or pattern', afebe2f.

=item B<fix -bos to keep isolated semicolon breaks after block braces>

The flag B<-bos>,  or B<--break-at-old-semicolon-breakpoints>, keeps breaks
at old isolated semicolons. For example

    $z = sqrt($x**2 + $y**2)
      ;

In testing it was found not to be doing this after braces which require
semicolons, such as 'do' and anonymous subs. This was fixed 12 Oct 2020 in
'fix -bos to work with semicolons after braces', 03ee7fc.  For example

    my $dist = sub {
        $z = sqrt( $x**2 + $y**2 )
          ;
      }
      ;

=item B<keep break after 'use overload'>

If a line break occurs after B<use overload> then it will now be kept. Previously
it was dropped.  For example, this would be kept intact:

                use overload
                    '+' => sub {
                        print length $_[2], "\n";
                        my ( $x, $y ) = _order(@_);
                        Number::Roman->new( int $x + $y );
                    },
                    '-' => sub {
                        my ( $x, $y ) = _order(@_);
                        Number::Roman->new( int $x - $y );
                    },
                    ...

This keeps the list from shifting to the right and can avoid problems in
formatting the list with certain styles, including with the -xci flag.
Fixed 12 Oct 2020 in 'keep break after use overload statement', 8485afa.

=item B<added flag -xci to improve formatting when -ci and -i are equal, issue git #28>

This flag causes continuation indentation to "extend" deeper into structures.
If you use B<-ci=n> and B<-i=n> with the same value of B<n> you will probably
want to set this flag.  Since this is a fairly new flag, the default is B<-nxci> 
to avoid disturbing existing formatting.  

=item B<terminal braces not indenting correctly with -bli formatting, issue git #40>

This problem is illustrated with the following snippet when run with -bli -blil='*'
 
    #-bli -bli list='*'
    try
      {
        die;
      }
    catch
      {
        die;
      };    # <-- this was not indenting

This was due to conflicting rules and was fixed 1 Oct 2020 in commit
'fix issue git #40, incorrect closing brace indentation with -bli', a5aefe9.

At the same time, it was noted that block types sort/map/grep and eval were not
following -bli formatting when -blil='*' and this was fixed.  For example, with
corrected formatting, we would have

  # perltidy -bli -blil='*'
    eval
      {
        my $app = App::perlbrew->new( "install-patchperl", "-q" );
        $app->run();
      }
      or do
      {
        $error          = $@;
        $produced_error = 1;
      };

=back

=head1 Issues fixed after release 20200907

This is a detailed log of changes since the release 20200907. All bugs were
found with the help of automated random testing.

=over

=item B<Keep any space between a bareword and quote>

In random testing, the -mangle option introduced a syntax error by deleting
the space between barewords and quotes (test file 'MxScreen'), such as:

  oops"Your login, $Bad_Login, is not valid";

Sub 'is_essential_whitespace' was updated to prevent this on 27 Sep 2020, 
in 'keep any space between a bareword and quote', f32553c.

=item B<Fixed some incorrect indentation disagreements reported in LOG file> 

The .LOG file reports any disagreements between the indentation of the input and output files.
This can help locate brace errors.  These were incorrect when some of the
options were used, including --whitespace-cycle, -bbhb, -nib.  This was
corrected 24 Sep 2020, 'fixed incorrect log entry for indentation
disagreement', 3d40545. At the same time, locations of closing brace
indentation disagreements are now tracked and reported in the .ERR file when
there is a brace error.  This can help localize the error if the file was
previously formatted by perltidy.

=item B<If an =cut starts a POD section within code, give a warning>

Previously only a complaint was given, which went into the log file and was not normally
seen.  Perl silently accepts this but it can cause significant problems with pod utilities, so
a clear warning is better.  This situation arose in testing on random files in combination with
a -dp flag and it took some time to understand the results because of the lack of a warning.

=item B<Switched from using an eval block to the ->can() function for sub finish_formatting>

This is not a bug, but is cleaner coding and insures that error messages get reported.
This change was made 20 Sep 2020, 'switch from eval { } to ->can('finish_formatting')', 28f2a4f.


=item B<fixed uninitialized value reference>

The following message was generated during automated testing

 Use of uninitialized value $cti in numeric eq (==) at /home/steve/bin/Perl/Tidy/Formatter.pm line 12079.
 Use of uninitialized value $cti in numeric eq (==) at /home/steve/bin/Perl/Tidy/Formatter.pm line 12089.
 Use of uninitialized value $cti in numeric eq (==) at /home/steve/bin/Perl/Tidy/Formatter.pm line 12097.

The problem could be simplified to running perltidy -wn on this snippet:

     __PACKAGE__->load_components( qw(
>         Core
> 
>     ) );

This was fixed 20 Sep 2020 in 'fixed_uninitialized_value', 8d6c4ed.

=item B<fix incorrect parsing of certain deprecated empty here-docs >

The following snippet was being incorrecly parsed:

 print <<
 # Hello World 13!
 
   ;
 print "DONE\n";

This is a deprecated here-doc without a specified target but currently still a
valid program.  It would have been correctly parsed if the semicolon followed 
the '<<' operator rather than the here-doc.  

This was found in random testing and fixed 16 Sep 2020.  A warning message about
deprecated here-doc targets was added.

=item B<make the arrow a vertical alignment token, git #39>

The -> can now be vertically aligned if a space is placed before it with -wls='->'.
Added 15 Sep 2020 as part of previous item, 9ac6af6.

=item B<add flags -bbhb=n, -bbsb=n, =bbp=n, git #38>

These flags give control over the opening token of a multiple-line list. They are
described in the man pages, perltidy.html.
Added 15 Sep 2020 in "added flags -bbhb=n, -bbsb=n, -bbq=n, suggestion git #38".
9ac6af6.

=item B<Allow vertical alignment of line-ending fat comma>

A change was made to allow a '=>' at the end of a line to align vertically, 
provided that it aligns with two or more other '=>' tokens.
This update was 14 Sep 2020, 'Allow line-ending '=>' to align vertically', ea96739.

=item B<fixed uninitialized value reference>

The following message was generated when running perltidy on random text:

 Use of uninitialized value $K_semicolon in subtraction (-) at /home/steve/bin/Perl/Tidy/Formatter.pm line 16467.

This was fixed 14 Sep 2020, included in 'Allow line-ending '=>' to align vertically', ea96739.

=item B<Do not create a zero size file by deleting semicolons>

A rule was added to prevent a file consisting of a single semicolon
  
 ;

from becoming a zero length file.  This could cause problems with other
software. Fixed 13 Sep 2020, 'do not create a zero length file by deleting semicolons', b39195e.

=item B<fixed uninitialized value reference>

The following message was generated when running perltidy on random text:

 Use of uninitialized value $cti in numeric eq (==) at /home/steve/bin/Perl/Tidy/Formatter.pm line 11926.
 Use of uninitialized value $cti in numeric eq (==) at /home/steve/bin/Perl/Tidy/Formatter.pm line 11936.
 Use of uninitialized value $cti in numeric eq (==) at /home/steve/bin/Perl/Tidy/Formatter.pm line 11944.

This was fixed 13 Sep 2020 in 'fixed unitialized variable problem ', adb2096.

=item B<fixed uninitialized value reference>

The following message was generated when running perltidy on random text:

 substr outside of string at /home/steve/bin/Perl/Tidy/Tokenizer.pm line 7362.
 Use of uninitialized value in concatenation (.) or string at /home/steve/bin/Perl/Tidy/Tokenizer.pm line 7362.

This was fixed 13 Sep 2020 in 'fixed unitialized variable problem', 5bf49a3.

=item B<fixed uninitialized value reference>

The following message was generated when running perltidy on random text:

 Use of uninitialized value $K_opening in subtraction (-) at /home/steve/bin/Perl/Tidy/Formatter.pm line 16467.

This was fixed 13 Sep 2020 in 'fix undefined variable reference', 1919482.

=item B<hashbang warning changed>

The following snippet generated a warning that there might be a hash-bang
after the start of the script.  

 $x = 2;
 #!  sunos does not yet provide a /usr/bin/perl
 $script = "$^X $script";

To prevent this annoyance, the warning is not given unless the first nonblank
character after the '#!' is a '/'.  Note that this change is just for the
warning message. The actual hash bang check does not require the slash.

Fixed 13 Sep 2020, 'prevent unnecessary hash-bang warning message' 4f7733e
and 'improved hash-bang warning filter', fa84904.

=item B<uninitialized index referenced>

An unitialized index was referenced when running on a file of randomly generated text:

  Use of uninitialized value $K_oo in subtraction (-) at /home/steve/bin/Perl/Tidy/Formatter.pm line 7259.

This was fixed 12 Sep 2020 in 'fixed undefined index', 616bb88.

=item B<Oops message triggered>

The parameter combination -lp -wc triggered an internal bug message from perltidy:

 398: Program bug with -lp.  seqno=77 should be 254 and i=1 should be less than max=-1
 713: The logfile perltidy.LOG may contain useful information
 713: 
 713: Oops, you seem to have encountered a bug in perltidy.  Please check the
 713: BUGS file at http://perltidy.sourceforge.net.  If the problem is not
 713: listed there, please report it so that it can be corrected.  Include the
 ...

The problem is that the parameters --line-up-parentheses and
--whitespace-cycle=n are not compatible.  The fix is to write a message and
turn off the -wc parameter when the both occur.  This was fixed 8 Sep 2020 in
"do not allow -wc and -lp together, can cause bugs", 7103781.

=item B<Internal fault detected by perltidy>

This snippet after processing with the indicated parameters triggered a Fault
message in store-token-to-go due to discontinuous internal index values :

  perltidy --noadd-newlines --space-terminal-semicolon

  if ( $_ =~ /PENCIL/ ) { $pencil_flag= 1 } ; ;
  $yy=1;

This triggered the message:

 ==============================================================================
 While operating on input stream with name: '<stdin>'
 A fault was detected at line 7472 of sub 'Perl::Tidy::Formatter::store_token_to_go'
 in file '/home/steve/bin/Perl/Tidy/Formatter.pm'
 which was called from line 8298 of sub 'Perl::Tidy::Formatter::process_line_of_CODE'
 Message: 'Unexpected break in K values: 591 != 589+1'
 This is probably an error introduced by a recent programming change. 
 ==============================================================================

The deletion of the extra, spaced, comma had created an extra space in the token array which
had not been forseen in the original programming. It was fixed 10 Sep 2020 in
"fixed very rare fault found with automated testing", eb1b1d9.

=item B<Error parsing deprecated $# variable>

This problem can be illustrated with this two-line snippet:

  $#
  eq$,?print"yes\n":print"no\n";

Perltidy joined '$#' and 'eq' to get $#eq, but should have stopped at the line end to
get $# followed by keyword 'eq'.  (Note that $# is deprecated). This was fixed 11 Sep 2020 in
"fixed several fringe parsing bugs found in testing", 85e01b7.

=item B<Error message parsing a file with angle brackets and ternaries>

This problem can be illustrated with the following test snippet which was not correctly parsed. 

 print$$ <300?"$$<300\n":$$<700?"$$<700\n":$$<2_000?"$$<2,000\n":$$<10_000?"$$ <10,000\n":"$$>9,999\n";

The problem is related to the '<' symbol following the '$$' variable, a possible filehandle,
and is similar to a previous bug. The problem was corrected 11 Sep 2020 in
"fixed several fringe parsing bugs found in testing", 85e01b7.  The line now correctly
formats to

 print $$ < 300  ? "$$<300\n"
   : $$ < 700    ? "$$<700\n"
   : $$ < 2_000  ? "$$<2,000\n"
   : $$ < 10_000 ? "$$ <10,000\n"
   :               "$$>9,999\n";


=item B<code crash with cuddled-else formatting on unbalanced files>

A file with incorrect bracing which effectively gave negative indentation
caused a crash when a stack was referenced with a negative index. The problem
was fixed 8 Sept 2020 in 
"convert array to hash to avoid trouble with neg levels in bad files", a720e0d.

=item B<error message 'Unterminated angle operator?'>

This error can be demonstrated with this line.

  print $i <10 ? "yes" : "no";

Perl has some strange parsing rules near a possible filehandle, and they change
over time. The '<' here is a less than symbol, but perltidy expected that it
might be the start of an angle operator, based on the old rules, and gave a
warning. The formatting was still correct, but the warning was confusing.  This
has been fixed 8 Sep 2020 in 'remove confusing warning message', 0a4d725.


=item B<Line broken after here target>

This problem is illustrated with the following snippet

  $sth= $dbh->prepare (<<"END_OF_SELECT") or die "Couldn't prepare SQL" ;
      SELECT COUNT(duration),SUM(duration) 
      FROM logins WHERE username='$user'
  END_OF_SELECT

When run with a short line length it got broken after the here target,
causing an error.  This was due to a recent program change and fixed
7 Sep 2020 in 'fixed bug where long line with here target got broken', 8f7e4cb.


=item B<undefined variable named 'test2'>

An uninitialized value was being referenced and triggered this message:

 undefined test2, i_opening=5, max=18, caller=Perl::Tidy::Formatter ./perltidy-20200907.pl 13465
 Use of uninitialized value $test2 in numeric eq (==) at ./perltidy-20200907.pl line 19692.

Fixed 8 Sep 2020 in 'fixed rare problem with stored index values for -lp option', 4147c8c.

=item B<Line order switched at start of quoted text>

This problem arose in several scripts involving the parameter
--line-up-parentheses pluse one or more of the vertical tightness flags.
It can be illustrated with the following snippet:

    perltidy --line-up-parentheses --paren-vertical-tightness=1

    if (
        ( $name, $chap ) =
        $cur_fname =~ m!^Bible/
	  .*?/		# testament
	  .*?/		# range of books
	  (.*?)/	# book name
	  .*?		# optional range of verses
	  (\d+)$!x
      )
    {
        $cur_name = "$name $chap";
    }

This gave 

    if (( $name, $chap ) =
	  .*?/		# testament
        $cur_fname =~ m!^Bible/
	  .*?/		# range of books
	  (.*?)/	# book name
	  .*?		# optional range of verses
	  (\d+)$!x
      )
    {
        $cur_name = "$name $chap";
    }

Notice the incorrect line order.  The problem was an incorrect order of
operations in the vertical aligner flush, leaving a line stranded and coming
out in the wrong order.  This was fixed 11 Sep 2020.

=item B<crash due to bad index named '$j_terminal_match'>

This crash was due to an index error which caused a non-existant object to be
referenced. The problem is fixed 2020-09-07 in "fix problem of undefined values involving j_terminal_match",
c5bfa77.  The particular parameters which caused this were:

    --noadd-newlines --nowant-left-space='=' 

=item B<an issue with the -x flag>

This is not a bug but did take some time to resolve.  The problem was reduced to the
following script run with the -x flag (--look-for-hash-bang)

 print(SCRIPT$headmaybe . <<EOB . <<'EOF' .$tailmaybe),$!;
 #!$wd/perl
 EOB
 print "\$^X is $^X, \$0 is $0\n";
 EOF

The resulting file had a syntax error (here-doc target EOB changed).

 print(SCRIPT$headmaybe . <<EOB . <<'EOF' .$tailmaybe),$!;
 #!$wd/perl
 EOB print "\$^X is $^X, \$0 is $0\n";
 EOF

The problem is that the -x flag tells perltidy not to start parsing until it sees a
line starting with '#!', which happens to be in a here-doc in this case.

A warning was added to the manual 7 Sept 2020 in "add warning about
inappropriate -x flag", fe66743.

=item B<error parsing sub signature>

This problem was reduced to the following snippet:

 substr
 (
  $#
 )

The deprecated variable '$#' was being parsed incorrectly, and this was due to an error
in which the word 'substr' followed by a paren was taken as the start of a sub signature.
The problem was fixed 8 Sep 2020 in 'fix problem parsing sub prototypes' 569e05f.
The code 

  $container_type =~ /^sub/;

was corrected to be

  $container_type =~ /^sub\b/;


=item B<uninitialized value message, found 7 Sep 2020>

Unitialized values were referenced.  An index was not being tested.
Fixed 8 Sep 2020 in "fix undefined variable", 9729965.

 Use of uninitialized value $Kon in array element at /home/steve/bin/Perl/Tidy/Formatter.pm line 4022.
 Use of uninitialized value $Kon in array element at /home/steve/bin/Perl/Tidy/Formatter.pm line 4023.
 Use of uninitialized value $Ko in subtraction (-) at /home/steve/bin/Perl/Tidy/Formatter.pm line 4023.

=back

=head1 Open Issues

These are known issues which have not been fixed.

=over 4

=item B<lexical subs not fully supported>

Basic parsing of lexical subs works but some aspects of lexical subs are not yet functional. 
One of these is that unlike regular subs, lexical subs can override names of builtin functions.

First consider the following snippet

  sub s { 
    my $arg=$_[0];
    print "s called with arg $arg\n";
  }
  s(1);
  s(2);

The 's' in the two last lines is the builtin s function, not the sub. Both perltidy and perl
make the same assumption here. This program happens to still run but prints nothing. It will
not run if the last semicolon is removed.

Now consider the following snippet in which the sub has a preceding 'my'

  use feature 'lexical_subs', 'signatures';
  my sub s { 
    my $arg=$_[0];
    print "s called with arg $arg\n";
  }
  s(1);
  s(2);

The builtin function 's' is replaced by the sub s here, and the program runs.  Perltidy
will format this but it is assuming that the s in the two last lines are the builtin s function.
If the last semicolon is removed, there will be an formatting error.  So perltidy and perl
make different assumptions in this case.

Another issue is that perltidy does not yet remember the extent of the scope of a lexical sub.

=item B<issues with paren-less calls>

Consider the following snippet:

  use Test::More;
  ok open($stdin, "<&", $1), 'open ... "<&", $magical_fileno', ||  _diag $!;

Note the unusual situation of a comma followed by an '||'.  Perltidy will format this
satisfactorally but it will write an error message. The syntax is correct, however.
Perl knows the prototype of the 'ok' function, which is called here without parens,
so the last comma marks the last arg and is needed to keep the || from attaching
to the last arg.

Full support of peren-less calls will probably never be implemented in perltidy
because it would require that it parse all of the modules used to find the
prototypes.  This would make it impossible to run perltidy on small snippets of code
from within an editor.

The problem can be avoid if parens are used:

  ok ( open($stdin, "<&", $1), 'open ... "<&", $magical_fileno') ||  _diag $!;

=item B<multiple sub paren calls>

Perltidy currently flags as an error a closing paren followed by an opening
paren, as in the following

  $subsubs[0]()(0)

This syntax is ok.  The example is from test 'current_sub.t' in perl5.31.

=back
