.PHONY : all
all:
	pod2html ../local-docs/stylekey.pod >stylekey.html
	pod2html ../local-docs/tutorial.pod >tutorial.html
	markdown ../INSTALL.md >INSTALL.html
	markdown ../CHANGES.md >ChangeLog.html
	pod2html ../bin/perltidy >perltidy.html
	pod2html ../lib/Perl/Tidy.pod >Tidy.html
	markdown index.md >index.html
