.PHONY : all
all:
	pod2markdown ../local-docs/INSTALL.pod >INSTALL.md
	pod2markdown ../local-docs/ChangeLog.pod >ChangeLog.md
	pod2markdown ../local-docs/stylekey.pod >stylekey.md
	pod2markdown ../local-docs/tutorial.pod >tutorial.md
	pod2markdown ../bin/perltidy >perltidy.md
	pod2markdown ../lib/Perl/Tidy.pod >Tidy.md
