.PHONY : all
all:
	pod2html ../local-docs/INSTALL.pod >INSTALL.html
	pod2html ../local-docs/ChangeLog.pod >ChangeLog.html
	pod2html ../local-docs/stylekey.pod >stylekey.html
	pod2html ../local-docs/tutorial.pod >tutorial.html
	pod2html ../bin/perltidy >perltidy.html
	pod2html ../lib/Perl/Tidy.pod >Tidy.html
	markdown index.md >index.html
